-- MySQL Script generated by MySQL Workbench
-- Wed Mar  1 13:31:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recadastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recadastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recadastro` DEFAULT CHARACTER SET utf8 ;
USE `recadastro` ;

-- -----------------------------------------------------
-- Table `recadastro`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recadastro`.`escolaridade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escolaridade` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recadastro`.`nacionalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recadastro`.`nacionalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nacionalidade` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recadastro`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recadastro`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(9) NULL,
  `logradouro` VARCHAR(45) NULL,
  `num` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recadastro`.`beneficiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recadastro`.`beneficiario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `nomeSocial` VARCHAR(150) NULL,
  `cpf` VARCHAR(18) NOT NULL,
  `rg` VARCHAR(18) NULL,
  `data_nascimento` DATE NULL,
  `telefone` VARCHAR(14) NULL,
  `email` VARCHAR(150) NULL,
  `pai` VARCHAR(150) NULL,
  `mae` VARCHAR(150) NULL,
  `etnia` VARCHAR(45) NULL,
  `raca` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `escolaridade_id` INT NOT NULL,
  `nacionalidade_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_beneficiario_escolaridade_idx` (`escolaridade_id` ASC) VISIBLE,
  INDEX `fk_beneficiario_nacionalidade1_idx` (`nacionalidade_id` ASC) VISIBLE,
  INDEX `fk_beneficiario_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_beneficiario_escolaridade`
    FOREIGN KEY (`escolaridade_id`)
    REFERENCES `recadastro`.`escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_beneficiario_nacionalidade1`
    FOREIGN KEY (`nacionalidade_id`)
    REFERENCES `recadastro`.`nacionalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_beneficiario_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `recadastro`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
